#!/bin/sh

DEBUG=false
for var in "$@"; do
  if [[ "${var}" = "-X" || "${var}" = "--debug" ]]; then
      DEBUG=true
  fi
done

# The command used to invoke this script. $0 returns an absolute or relative path to this script. ${0##*/} returns just the script name.
CMD=${0##*/}

# Search for the directory containing the .mvn in the current directory and ancestor directories.
path=$(pwd)
while [[ "$path" != "" && ! -e "$path/.mvn" ]]; do
  path=${path%/*}
done

MVN_ENV_DIR=${path}/.mvn
if [ ! -e "${MVN_ENV_DIR}" ]; then
  if [ ${DEBUG} = true ]; then echo "No .mvn directory found. Executing default '${CMD}' command."; fi
  if [ ${DEBUG} = true ]; then set -x; fi
  ${CMD} "$@"
  exit $?
fi

if [ ! -e "${MVN_ENV_DIR}/m2_home" ]; then
  if [ ${DEBUG} = true ]; then
    echo "Please define a symlink to your Maven Home directory like so:"
    echo "$ ln -s /path/to/apache-maven-X.Y.Z /path/to/project/.mvn/m2_home"
    echo ""
    echo "You can also define a custom Maven User/Global settings by doing:"
    echo "$ ln -s /path/to/my_user_settings.xml /path/to/project/.mvn/user_settings.xml"
    echo "$ ln -s /path/to/my_global_settings.xml /path/to/project/.mvn/global_settings.xml"
    echo ""
    echo "You can also define a custom JAVA_HOME like so:"
    echo "$ ln -s /path/to/java /path/to/project/.mvn/java_home"
    echo ""
  fi
  exit 1
fi

M2_HOME="${MVN_ENV_DIR}/m2_home"
USER_SETTINGS="${MVN_ENV_DIR}/user_settings.xml"
GLOBAL_SETTINGS="${MVN_ENV_DIR}/global_settings.xml"

PARAMS=""x
if [ -e "$USER_SETTINGS" ]; then
  PARAMS="-s ${USER_SETTINGS}"
  if [ ${DEBUG} = true ]; then echo "Apache Maven User Settings: ${USER_SETTINGS}"; fi
fi

if [ -e "$GLOBAL_SETTINGS" ]; then
  params="${PARAMS} -gs ${GLOBAL_SETTINGS}"
  if [ ${DEBUG} = true ]; then echo "Apache Maven Global Settings: ${GLOBAL_SETTINGS}"; fi
fi

if [ -e "$MVN_ENV_DIR/java_home" ]; then
  JAVA_HOME="$MVN_ENV_DIR/java_home"
  if [ ${DEBUG} = true ]; then echo "Java home: ${JAVA_HOME}"; fi
fi

if [ ${DEBUG} = true ]; then set -x; fi
${CMD} ${PARAMS} "$@"
exit $?
